# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\Python\MCSL2\Resources\QtUIFiles\MCSL2_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MCSL2_Dialog(object):
    def setupUi(self, MCSL2_Dialog):
        MCSL2_Dialog.setObjectName("MCSL2_Dialog")
        MCSL2_Dialog.resize(413, 242)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MCSL2_Dialog.setWindowIcon(icon)
        self.Dialog_PushButton = QtWidgets.QPushButton(MCSL2_Dialog)
        self.Dialog_PushButton.setGeometry(QtCore.QRect(160, 190, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Dialog_PushButton.setFont(font)
        self.Dialog_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Dialog_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 7px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 110, 212);\n"
"    border-radius: 7px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 100, 212);\n"
"    border-radius: 7px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Dialog_PushButton.setObjectName("Dialog_PushButton")
        self.Dialog_label = QtWidgets.QLabel(MCSL2_Dialog)
        self.Dialog_label.setGeometry(QtCore.QRect(30, 20, 351, 151))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.Dialog_label.setFont(font)
        self.Dialog_label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px\n"
"}")
        self.Dialog_label.setText("")
        self.Dialog_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Dialog_label.setObjectName("Dialog_label")
        self.Background = QtWidgets.QLabel(MCSL2_Dialog)
        self.Background.setGeometry(QtCore.QRect(0, 0, 413, 242))
        self.Background.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgba(247, 247, 247,85%);\n"
"}")
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.Background.raise_()
        self.Dialog_PushButton.raise_()
        self.Dialog_label.raise_()

        self.retranslateUi(MCSL2_Dialog)
        QtCore.QMetaObject.connectSlotsByName(MCSL2_Dialog)

    def retranslateUi(self, MCSL2_Dialog):
        _translate = QtCore.QCoreApplication.translate
        MCSL2_Dialog.setWindowTitle(_translate("MCSL2_Dialog", "提示"))
        self.Dialog_PushButton.setText(_translate("MCSL2_Dialog", "知道了"))
import MCSL2_Icon_rc
