# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\MCSLCode\MCSL2\Resources\QtUIFiles\MCSL2_AskDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import MCSL2_Icon_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MCSL2_AskDialog(object):
    def setupUi(self, MCSL2_AskDialog):
        MCSL2_AskDialog.setObjectName("MCSL2_AskDialog")
        MCSL2_AskDialog.resize(413, 260)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            MCSL2_AskDialog.sizePolicy().hasHeightForWidth())
        MCSL2_AskDialog.setSizePolicy(sizePolicy)
        MCSL2_AskDialog.setMinimumSize(QtCore.QSize(413, 260))
        MCSL2_AskDialog.setMaximumSize(QtCore.QSize(413, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"),
                       QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"),
                       QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"),
                       QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"),
                       QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"),
                       QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"),
                       QtGui.QIcon.Selected, QtGui.QIcon.On)
        MCSL2_AskDialog.setWindowIcon(icon)
        MCSL2_AskDialog.setStyleSheet("QDialog\n"
                                      "{\n"
                                      "    background-color: rgba(247, 247, 247,85%);\n"
                                      "}")
        self.gridLayout = QtWidgets.QGridLayout(MCSL2_AskDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.Dialog_label = QtWidgets.QLabel(MCSL2_AskDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Dialog_label.sizePolicy().hasHeightForWidth())
        self.Dialog_label.setSizePolicy(sizePolicy)
        self.Dialog_label.setMinimumSize(QtCore.QSize(351, 151))
        self.Dialog_label.setMaximumSize(QtCore.QSize(351, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.Dialog_label.setFont(font)
        self.Dialog_label.setStyleSheet("QLabel\n"
                                        "{\n"
                                        "    background-color: rgb(255, 255, 255);\n"
                                        "    border-radius: 10px\n"
                                        "}")
        self.Dialog_label.setText("")
        self.Dialog_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Dialog_label.setObjectName("Dialog_label")
        self.gridLayout.addWidget(self.Dialog_label, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.ButtonWidget = QtWidgets.QWidget(MCSL2_AskDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(35)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(
            self.ButtonWidget.sizePolicy().hasHeightForWidth())
        self.ButtonWidget.setSizePolicy(sizePolicy)
        self.ButtonWidget.setMinimumSize(QtCore.QSize(351, 40))
        self.ButtonWidget.setMaximumSize(QtCore.QSize(351, 40))
        self.ButtonWidget.setObjectName("ButtonWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ButtonWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Dialog_PushButton_Cancel = QtWidgets.QPushButton(
            self.ButtonWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Dialog_PushButton_Cancel.sizePolicy().hasHeightForWidth())
        self.Dialog_PushButton_Cancel.setSizePolicy(sizePolicy)
        self.Dialog_PushButton_Cancel.setMinimumSize(QtCore.QSize(165, 31))
        self.Dialog_PushButton_Cancel.setMaximumSize(QtCore.QSize(170, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Dialog_PushButton_Cancel.setFont(font)
        self.Dialog_PushButton_Cancel.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Dialog_PushButton_Cancel.setStyleSheet("QPushButton\n"
                                                    "{\n"
                                                    "    background-color: rgb(255, 255, 255);\n"
                                                    "    border-radius: 7px;\n"
                                                    "}\n"
                                                    "QPushButton:hover\n"
                                                    "{\n"
                                                    "    background-color: rgb(240, 240, 240);\n"
                                                    "    border-radius: 7px;\n"
                                                    "}\n"
                                                    "QPushButton:pressed\n"
                                                    "{\n"
                                                    "    background-color: rgb(229, 229, 229);\n"
                                                    "    border-radius: 7px;\n"
                                                    "}")
        self.Dialog_PushButton_Cancel.setObjectName("Dialog_PushButton_Cancel")
        self.horizontalLayout.addWidget(self.Dialog_PushButton_Cancel)
        self.Dialog_PushButton_Accept = QtWidgets.QPushButton(
            self.ButtonWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Dialog_PushButton_Accept.sizePolicy().hasHeightForWidth())
        self.Dialog_PushButton_Accept.setSizePolicy(sizePolicy)
        self.Dialog_PushButton_Accept.setMinimumSize(QtCore.QSize(160, 31))
        self.Dialog_PushButton_Accept.setMaximumSize(QtCore.QSize(170, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Dialog_PushButton_Accept.setFont(font)
        self.Dialog_PushButton_Accept.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Dialog_PushButton_Accept.setStyleSheet("QPushButton\n"
                                                    "{\n"
                                                    "    background-color: rgb(0, 120, 212);\n"
                                                    "    border-radius: 7px;\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}\n"
                                                    "QPushButton:hover\n"
                                                    "{\n"
                                                    "    background-color: rgb(0, 110, 212);\n"
                                                    "    border-radius: 7px;\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}\n"
                                                    "QPushButton:pressed\n"
                                                    "{\n"
                                                    "    background-color: rgb(0, 100, 212);\n"
                                                    "    border-radius: 7px;\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}")
        self.Dialog_PushButton_Accept.setObjectName("Dialog_PushButton_Accept")
        self.horizontalLayout.addWidget(self.Dialog_PushButton_Accept)
        self.gridLayout.addWidget(self.ButtonWidget, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)

        self.retranslateUi(MCSL2_AskDialog)
        QtCore.QMetaObject.connectSlotsByName(MCSL2_AskDialog)

    def retranslateUi(self, MCSL2_AskDialog):
        _translate = QtCore.QCoreApplication.translate
        MCSL2_AskDialog.setWindowTitle(_translate("MCSL2_AskDialog", "提示"))
        self.Dialog_PushButton_Cancel.setText(
            _translate("MCSL2_AskDialog", "取消"))
        self.Dialog_PushButton_Accept.setText(
            _translate("MCSL2_AskDialog", "确定"))
