# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\MCSLCode\MCSL2\Resources\QtUIFiles\MCSL2_SubWidgets.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MCSL2_SubWidget_Select = QtWidgets.QWidget(self.centralwidget)
        self.MCSL2_SubWidget_Select.setGeometry(QtCore.QRect(150, 110, 620, 70))
        self.MCSL2_SubWidget_Select.setMinimumSize(QtCore.QSize(620, 70))
        self.MCSL2_SubWidget_Select.setMaximumSize(QtCore.QSize(620, 70))
        self.MCSL2_SubWidget_Select.setStyleSheet("QWidget\n"
"{\n"
"    border-radius: 4px;\n"
"    background-color: rgba(247, 247, 247, 247)\n"
"}")
        self.MCSL2_SubWidget_Select.setObjectName("MCSL2_SubWidget_Select")
        self.Select_PushButton = QtWidgets.QPushButton(self.MCSL2_SubWidget_Select)
        self.Select_PushButton.setGeometry(QtCore.QRect(540, 10, 51, 51))
        self.Select_PushButton.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Select_PushButton.setFont(font)
        self.Select_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Select_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 110, 212);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 100, 212);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Select_PushButton.setFlat(False)
        self.Select_PushButton.setObjectName("Select_PushButton")
        self.IntroductionWidget_S = QtWidgets.QWidget(self.MCSL2_SubWidget_Select)
        self.IntroductionWidget_S.setGeometry(QtCore.QRect(100, 10, 421, 51))
        self.IntroductionWidget_S.setMinimumSize(QtCore.QSize(421, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.IntroductionWidget_S.setFont(font)
        self.IntroductionWidget_S.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 8px\n"
"}")
        self.IntroductionWidget_S.setObjectName("IntroductionWidget_S")
        self.IntroductionLabel_S = QtWidgets.QLabel(self.IntroductionWidget_S)
        self.IntroductionLabel_S.setGeometry(QtCore.QRect(10, 0, 401, 51))
        self.IntroductionLabel_S.setMinimumSize(QtCore.QSize(401, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.IntroductionLabel_S.setFont(font)
        self.IntroductionLabel_S.setText("")
        self.IntroductionLabel_S.setObjectName("IntroductionLabel_S")
        self.GraphWidget_S = QtWidgets.QLabel(self.MCSL2_SubWidget_Select)
        self.GraphWidget_S.setGeometry(QtCore.QRect(30, 10, 51, 51))
        self.GraphWidget_S.setMinimumSize(QtCore.QSize(51, 51))
        self.GraphWidget_S.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 4px;\n"
"}")
        self.GraphWidget_S.setText("")
        self.GraphWidget_S.setScaledContents(True)
        self.GraphWidget_S.setObjectName("GraphWidget_S")
        self.MCSL2_SubWidget_Download = QtWidgets.QWidget(self.centralwidget)
        self.MCSL2_SubWidget_Download.setGeometry(QtCore.QRect(150, 190, 620, 70))
        self.MCSL2_SubWidget_Download.setMinimumSize(QtCore.QSize(620, 70))
        self.MCSL2_SubWidget_Download.setMaximumSize(QtCore.QSize(620, 70))
        self.MCSL2_SubWidget_Download.setStyleSheet("QWidget\n"
"{\n"
"    border-radius: 4px;\n"
"    background-color: rgba(247, 247, 247, 247)\n"
"}")
        self.MCSL2_SubWidget_Download.setObjectName("MCSL2_SubWidget_Download")
        self.IntroductionWidget_D = QtWidgets.QWidget(self.MCSL2_SubWidget_Download)
        self.IntroductionWidget_D.setGeometry(QtCore.QRect(100, 10, 421, 51))
        self.IntroductionWidget_D.setMinimumSize(QtCore.QSize(421, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.IntroductionWidget_D.setFont(font)
        self.IntroductionWidget_D.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 8px\n"
"}")
        self.IntroductionWidget_D.setObjectName("IntroductionWidget_D")
        self.IntroductionLabel_D = QtWidgets.QLabel(self.IntroductionWidget_D)
        self.IntroductionLabel_D.setGeometry(QtCore.QRect(10, 0, 401, 51))
        self.IntroductionLabel_D.setMinimumSize(QtCore.QSize(401, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.IntroductionLabel_D.setFont(font)
        self.IntroductionLabel_D.setText("")
        self.IntroductionLabel_D.setObjectName("IntroductionLabel_D")
        self.Download_PushButton = QtWidgets.QPushButton(self.MCSL2_SubWidget_Download)
        self.Download_PushButton.setGeometry(QtCore.QRect(540, 10, 51, 51))
        self.Download_PushButton.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Download_PushButton.setFont(font)
        self.Download_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Download_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 110, 212);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 100, 212);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Download_PushButton.setFlat(False)
        self.Download_PushButton.setObjectName("Download_PushButton")
        self.GraphWidget_D = QtWidgets.QLabel(self.MCSL2_SubWidget_Download)
        self.GraphWidget_D.setGeometry(QtCore.QRect(30, 10, 51, 51))
        self.GraphWidget_D.setMinimumSize(QtCore.QSize(51, 51))
        self.GraphWidget_D.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 4px;\n"
"}")
        self.GraphWidget_D.setText("")
        self.GraphWidget_D.setScaledContents(True)
        self.GraphWidget_D.setObjectName("GraphWidget_D")
        self.MCSL2_SubWidget_SelectS = QtWidgets.QWidget(self.centralwidget)
        self.MCSL2_SubWidget_SelectS.setGeometry(QtCore.QRect(150, 270, 620, 171))
        self.MCSL2_SubWidget_SelectS.setMinimumSize(QtCore.QSize(620, 171))
        self.MCSL2_SubWidget_SelectS.setMaximumSize(QtCore.QSize(620, 171))
        self.MCSL2_SubWidget_SelectS.setStyleSheet("QWidget\n"
"{\n"
"    border-radius: 4px;\n"
"    background-color: rgba(247, 247, 247, 247)\n"
"}")
        self.MCSL2_SubWidget_SelectS.setObjectName("MCSL2_SubWidget_SelectS")
        self.SelectS_PushButton = QtWidgets.QPushButton(self.MCSL2_SubWidget_SelectS)
        self.SelectS_PushButton.setGeometry(QtCore.QRect(550, 60, 51, 51))
        self.SelectS_PushButton.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.SelectS_PushButton.setFont(font)
        self.SelectS_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SelectS_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 110, 212);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 100, 212);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.SelectS_PushButton.setFlat(False)
        self.SelectS_PushButton.setObjectName("SelectS_PushButton")
        self.IntroductionWidget_SS = QtWidgets.QWidget(self.MCSL2_SubWidget_SelectS)
        self.IntroductionWidget_SS.setGeometry(QtCore.QRect(80, 10, 451, 151))
        self.IntroductionWidget_SS.setMinimumSize(QtCore.QSize(421, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.IntroductionWidget_SS.setFont(font)
        self.IntroductionWidget_SS.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 8px\n"
"}")
        self.IntroductionWidget_SS.setObjectName("IntroductionWidget_SS")
        self.IntroductionLabel_SS = QtWidgets.QLabel(self.IntroductionWidget_SS)
        self.IntroductionLabel_SS.setGeometry(QtCore.QRect(10, 5, 431, 141))
        self.IntroductionLabel_SS.setMinimumSize(QtCore.QSize(401, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.IntroductionLabel_SS.setFont(font)
        self.IntroductionLabel_SS.setText("")
        self.IntroductionLabel_SS.setObjectName("IntroductionLabel_SS")
        self.GraphWidget_SS = QtWidgets.QLabel(self.MCSL2_SubWidget_SelectS)
        self.GraphWidget_SS.setGeometry(QtCore.QRect(20, 60, 51, 51))
        self.GraphWidget_SS.setMinimumSize(QtCore.QSize(51, 51))
        self.GraphWidget_SS.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 4px;\n"
"}")
        self.GraphWidget_SS.setText("")
        self.GraphWidget_SS.setScaledContents(True)
        self.GraphWidget_SS.setObjectName("GraphWidget_SS")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Select_PushButton.setText(_translate("MainWindow", "选择"))
        self.Download_PushButton.setText(_translate("MainWindow", "下载"))
        self.SelectS_PushButton.setText(_translate("MainWindow", "选择"))
