# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\MCSLCode\MCSL2\Resources\QtUIFiles\MCSL2_DownloadProgress.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MCSL2_DownloadProgress(object):
    def setupUi(self, MCSL2_DownloadProgress):
        MCSL2_DownloadProgress.setObjectName("MCSL2_DownloadProgress")
        MCSL2_DownloadProgress.resize(962, 601)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            MCSL2_DownloadProgress.sizePolicy().hasHeightForWidth())
        MCSL2_DownloadProgress.setSizePolicy(sizePolicy)
        MCSL2_DownloadProgress.setMinimumSize(QtCore.QSize(962, 601))
        MCSL2_DownloadProgress.setMaximumSize(QtCore.QSize(962, 601))
        self.Shadow = QtWidgets.QLabel(MCSL2_DownloadProgress)
        self.Shadow.setGeometry(QtCore.QRect(8, 8, 945, 585))
        self.Shadow.setStyleSheet("QLabel\n"
                                  "{\n"
                                  "    background-color: rgba(230, 230, 230, 15%);\n"
                                  "    border-radius: 10px\n"
                                  "}")
        self.Shadow.setText("")
        self.Shadow.setObjectName("Shadow")
        self.DownloadProgressWidget = QtWidgets.QWidget(MCSL2_DownloadProgress)
        self.DownloadProgressWidget.setGeometry(QtCore.QRect(8, 8, 945, 585))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.DownloadProgressWidget.sizePolicy().hasHeightForWidth())
        self.DownloadProgressWidget.setSizePolicy(sizePolicy)
        self.DownloadProgressWidget.setMinimumSize(QtCore.QSize(945, 585))
        self.DownloadProgressWidget.setMaximumSize(QtCore.QSize(945, 585))
        self.DownloadProgressWidget.setStyleSheet("QWidget\n"
                                                  "{\n"
                                                  "    border-radius: 4px;\n"
                                                  "    background-color: transparent;\n"
                                                  "}")
        self.DownloadProgressWidget.setObjectName("DownloadProgressWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.DownloadProgressWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.RealDownloadProgress = QtWidgets.QWidget(
            self.DownloadProgressWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.RealDownloadProgress.sizePolicy().hasHeightForWidth())
        self.RealDownloadProgress.setSizePolicy(sizePolicy)
        self.RealDownloadProgress.setMinimumSize(QtCore.QSize(441, 181))
        self.RealDownloadProgress.setMaximumSize(QtCore.QSize(441, 181))
        self.RealDownloadProgress.setStyleSheet("QWidget\n"
                                                "{\n"
                                                "    border-radius: 4px;\n"
                                                "    background-color: rgba(247, 247, 247, 247)\n"
                                                "}")
        self.RealDownloadProgress.setObjectName("RealDownloadProgress")
        self.GraphWidget_DownloadProgress = QtWidgets.QLabel(
            self.RealDownloadProgress)
        self.GraphWidget_DownloadProgress.setGeometry(
            QtCore.QRect(30, 65, 51, 51))
        self.GraphWidget_DownloadProgress.setMinimumSize(QtCore.QSize(51, 51))
        self.GraphWidget_DownloadProgress.setStyleSheet("QLabel\n"
                                                        "{\n"
                                                        "    background-color: rgb(247, 247, 247);\n"
                                                        "    border-radius: 4px;\n"
                                                        "}")
        self.GraphWidget_DownloadProgress.setText("")
        self.GraphWidget_DownloadProgress.setScaledContents(True)
        self.GraphWidget_DownloadProgress.setObjectName(
            "GraphWidget_DownloadProgress")
        self.DownloadingFileNameLabel = QtWidgets.QLabel(
            self.RealDownloadProgress)
        self.DownloadingFileNameLabel.setGeometry(
            QtCore.QRect(110, 35, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.DownloadingFileNameLabel.setFont(font)
        self.DownloadingFileNameLabel.setTextFormat(QtCore.Qt.PlainText)
        self.DownloadingFileNameLabel.setScaledContents(True)
        self.DownloadingFileNameLabel.setObjectName("DownloadingFileNameLabel")
        self.DownloadingSpeedLabel = QtWidgets.QLabel(
            self.RealDownloadProgress)
        self.DownloadingSpeedLabel.setGeometry(QtCore.QRect(110, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.DownloadingSpeedLabel.setFont(font)
        self.DownloadingSpeedLabel.setTextFormat(QtCore.Qt.PlainText)
        self.DownloadingSpeedLabel.setScaledContents(True)
        self.DownloadingSpeedLabel.setObjectName("DownloadingSpeedLabel")
        self.CancelDownloadPushButton = QtWidgets.QPushButton(
            self.RealDownloadProgress)
        self.CancelDownloadPushButton.setGeometry(
            QtCore.QRect(340, 130, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.CancelDownloadPushButton.setFont(font)
        self.CancelDownloadPushButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CancelDownloadPushButton.setStyleSheet("QPushButton\n"
                                                    "{\n"
                                                    "    background-color: rgb(0, 120, 212);\n"
                                                    "    border-radius: 6px;\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}\n"
                                                    "QPushButton:hover\n"
                                                    "{\n"
                                                    "    background-color: rgb(0, 110, 212);\n"
                                                    "    border-radius: 6px;\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}\n"
                                                    "QPushButton:pressed\n"
                                                    "{\n"
                                                    "    background-color: rgb(0, 100, 212);\n"
                                                    "    border-radius: 6px;\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}")
        self.CancelDownloadPushButton.setFlat(False)
        self.CancelDownloadPushButton.setObjectName("CancelDownloadPushButton")
        self.DownloadingInfoWidget = QtWidgets.QWidget(
            self.RealDownloadProgress)
        self.DownloadingInfoWidget.setGeometry(QtCore.QRect(110, 70, 310, 26))
        self.DownloadingInfoWidget.setObjectName("DownloadingInfoWidget")
        self.DownloadingPercentLabel = QtWidgets.QLabel(
            self.DownloadingInfoWidget)
        self.DownloadingPercentLabel.setGeometry(QtCore.QRect(270, 0, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.DownloadingPercentLabel.setFont(font)
        self.DownloadingPercentLabel.setTextFormat(QtCore.Qt.PlainText)
        self.DownloadingPercentLabel.setScaledContents(True)
        self.DownloadingPercentLabel.setObjectName("DownloadingPercentLabel")
        self.gridLayout.addWidget(self.RealDownloadProgress, 0, 0, 1, 1)

        self.retranslateUi(MCSL2_DownloadProgress)
        QtCore.QMetaObject.connectSlotsByName(MCSL2_DownloadProgress)

    def retranslateUi(self, MCSL2_DownloadProgress):
        _translate = QtCore.QCoreApplication.translate
        self.DownloadingFileNameLabel.setText(
            _translate("MCSL2_DownloadProgress", "正在下载："))
        self.DownloadingSpeedLabel.setText(
            _translate("MCSL2_DownloadProgress", "速度："))
        self.CancelDownloadPushButton.setText(
            _translate("MCSL2_DownloadProgress", "取消"))
        self.DownloadingPercentLabel.setText(
            _translate("MCSL2_DownloadProgress", "%"))
