# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\Python\MCSL2\MCSL2_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MCSL2_Dialog(object):
    def setupUi(self, MCSL2_Dialog):
        MCSL2_Dialog.setObjectName("MCSL2_Dialog")
        MCSL2_Dialog.resize(340, 196)
        self.Dialog_PushButton = QtWidgets.QPushButton(MCSL2_Dialog)
        self.Dialog_PushButton.setGeometry(QtCore.QRect(110, 130, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Dialog_PushButton.setFont(font)
        self.Dialog_PushButton.setStyleSheet("QPushButton\n"
                                             "{\n"
                                             "    background-color: rgb(230, 230, 230);\n"
                                             "    border-radius: 7px;\n"
                                             "}\n"
                                             "QPushButton:pressed\n"
                                             "{\n"
                                             "    background-color: rgb(223, 223, 223);\n"
                                             "    border-radius: 7px;\n"
                                             "}")
        self.Dialog_PushButton.setObjectName("Dialog_PushButton")
        self.Dialog_label = QtWidgets.QLabel(MCSL2_Dialog)
        self.Dialog_label.setGeometry(QtCore.QRect(30, 20, 281, 101))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.Dialog_label.setFont(font)
        self.Dialog_label.setText("")
        self.Dialog_label.setObjectName("Dialog_label")
        self.setWindowFlags(Qt.WindowCloseButtonHint)
        self.retranslateUi(MCSL2_Dialog)
        QtCore.QMetaObject.connectSlotsByName(MCSL2_Dialog)

    def retranslateUi(self, MCSL2_Dialog):
        _translate = QtCore.QCoreApplication.translate
        MCSL2_Dialog.setWindowTitle(_translate("MCSL2_Dialog", "提示"))
        self.Dialog_PushButton.setText(_translate("MCSL2_Dialog", "知道了"))

        self.Dialog_PushButton.clicked.connect(self.close)
