# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\Python\MCSL2\resources\MCSL2_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MCSL2_MainWindow(object):
    def setupUi(self, MCSL2_MainWindow):
        MCSL2_MainWindow.setObjectName("MCSL2_MainWindow")
        MCSL2_MainWindow.resize(944, 583)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MCSL2_MainWindow.setWindowIcon(icon)
        self.CentralWidget = QtWidgets.QWidget(MCSL2_MainWindow)
        self.CentralWidget.setObjectName("CentralWidget")
        self.OptionsWidget = QtWidgets.QWidget(self.CentralWidget)
        self.OptionsWidget.setGeometry(QtCore.QRect(0, 0, 211, 581))
        self.OptionsWidget.setObjectName("OptionsWidget")
        self.Close_PushButton = QtWidgets.QPushButton(self.OptionsWidget)
        self.Close_PushButton.setGeometry(QtCore.QRect(20, 20, 31, 23))
        self.Close_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Close_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(232, 17, 35);\n"
"    border-radius: 11px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(193, 6, 16);\n"
"    border-radius: 11px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(170, 0, 0);\n"
"    border-radius: 11px;\n"
"}")
        self.Close_PushButton.setText("")
        self.Close_PushButton.setObjectName("Close_PushButton")
        self.Minimize_PushButton = QtWidgets.QPushButton(self.OptionsWidget)
        self.Minimize_PushButton.setGeometry(QtCore.QRect(60, 20, 31, 23))
        self.Minimize_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Minimize_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(225, 225, 0);\n"
"    border-radius: 11px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(183, 161, 0);\n"
"    border-radius: 11px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(161, 161, 0);\n"
"    border-radius: 11px;\n"
"}")
        self.Minimize_PushButton.setText("")
        self.Minimize_PushButton.setObjectName("Minimize_PushButton")
        self.Home_Page_PushButton = QtWidgets.QPushButton(self.OptionsWidget)
        self.Home_Page_PushButton.setEnabled(True)
        self.Home_Page_PushButton.setGeometry(QtCore.QRect(20, 140, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        self.Home_Page_PushButton.setFont(font)
        self.Home_Page_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Home_Page_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(243, 243, 243);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(233, 233, 233);\n"
"    border-radius: 7px;\n"
"}")
        self.Home_Page_PushButton.setCheckable(False)
        self.Home_Page_PushButton.setChecked(False)
        self.Home_Page_PushButton.setAutoExclusive(False)
        self.Home_Page_PushButton.setObjectName("Home_Page_PushButton")
        self.Config_Page_PushButton = QtWidgets.QPushButton(self.OptionsWidget)
        self.Config_Page_PushButton.setEnabled(True)
        self.Config_Page_PushButton.setGeometry(QtCore.QRect(20, 200, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        self.Config_Page_PushButton.setFont(font)
        self.Config_Page_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Config_Page_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(243, 243, 243);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(233, 233, 233);\n"
"    border-radius: 7px;\n"
"}")
        self.Config_Page_PushButton.setCheckable(False)
        self.Config_Page_PushButton.setChecked(False)
        self.Config_Page_PushButton.setAutoExclusive(False)
        self.Config_Page_PushButton.setObjectName("Config_Page_PushButton")
        self.MCSL2_Title_Label = QtWidgets.QLabel(self.OptionsWidget)
        self.MCSL2_Title_Label.setGeometry(QtCore.QRect(100, 60, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.MCSL2_Title_Label.setFont(font)
        self.MCSL2_Title_Label.setObjectName("MCSL2_Title_Label")
        self.MCSL2_Title_Author_Label = QtWidgets.QLabel(self.OptionsWidget)
        self.MCSL2_Title_Author_Label.setGeometry(QtCore.QRect(100, 90, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.MCSL2_Title_Author_Label.setFont(font)
        self.MCSL2_Title_Author_Label.setObjectName("MCSL2_Title_Author_Label")
        self.MCSL2_Title_Icon_Label = QtWidgets.QLabel(self.OptionsWidget)
        self.MCSL2_Title_Icon_Label.setGeometry(QtCore.QRect(20, 50, 71, 71))
        self.MCSL2_Title_Icon_Label.setStyleSheet("")
        self.MCSL2_Title_Icon_Label.setText("")
        self.MCSL2_Title_Icon_Label.setPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"))
        self.MCSL2_Title_Icon_Label.setScaledContents(True)
        self.MCSL2_Title_Icon_Label.setObjectName("MCSL2_Title_Icon_Label")
        self.Download_Page_PushButton = QtWidgets.QPushButton(self.OptionsWidget)
        self.Download_Page_PushButton.setEnabled(True)
        self.Download_Page_PushButton.setGeometry(QtCore.QRect(20, 260, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        self.Download_Page_PushButton.setFont(font)
        self.Download_Page_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Download_Page_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(243, 243, 243);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(233, 233, 233);\n"
"    border-radius: 7px;\n"
"}")
        self.Download_Page_PushButton.setCheckable(False)
        self.Download_Page_PushButton.setChecked(False)
        self.Download_Page_PushButton.setAutoExclusive(False)
        self.Download_Page_PushButton.setObjectName("Download_Page_PushButton")
        self.Server_Console_Page_PushButton = QtWidgets.QPushButton(self.OptionsWidget)
        self.Server_Console_Page_PushButton.setEnabled(True)
        self.Server_Console_Page_PushButton.setGeometry(QtCore.QRect(20, 320, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        self.Server_Console_Page_PushButton.setFont(font)
        self.Server_Console_Page_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Server_Console_Page_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(243, 243, 243);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(233, 233, 233);\n"
"    border-radius: 7px;\n"
"}")
        self.Server_Console_Page_PushButton.setCheckable(False)
        self.Server_Console_Page_PushButton.setChecked(False)
        self.Server_Console_Page_PushButton.setAutoExclusive(False)
        self.Server_Console_Page_PushButton.setObjectName("Server_Console_Page_PushButton")
        self.Tools_Page_PushButton = QtWidgets.QPushButton(self.OptionsWidget)
        self.Tools_Page_PushButton.setEnabled(True)
        self.Tools_Page_PushButton.setGeometry(QtCore.QRect(20, 380, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        self.Tools_Page_PushButton.setFont(font)
        self.Tools_Page_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tools_Page_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(243, 243, 243);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(233, 233, 233);\n"
"    border-radius: 7px;\n"
"}")
        self.Tools_Page_PushButton.setCheckable(False)
        self.Tools_Page_PushButton.setChecked(False)
        self.Tools_Page_PushButton.setAutoExclusive(False)
        self.Tools_Page_PushButton.setObjectName("Tools_Page_PushButton")
        self.About_Page_PushButton = QtWidgets.QPushButton(self.OptionsWidget)
        self.About_Page_PushButton.setEnabled(True)
        self.About_Page_PushButton.setGeometry(QtCore.QRect(20, 440, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        self.About_Page_PushButton.setFont(font)
        self.About_Page_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.About_Page_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(243, 243, 243);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(233, 233, 233);\n"
"    border-radius: 7px;\n"
"}")
        self.About_Page_PushButton.setCheckable(False)
        self.About_Page_PushButton.setChecked(False)
        self.About_Page_PushButton.setAutoExclusive(False)
        self.About_Page_PushButton.setObjectName("About_Page_PushButton")
        self.Blue1 = QtWidgets.QLabel(self.OptionsWidget)
        self.Blue1.setEnabled(True)
        self.Blue1.setGeometry(QtCore.QRect(20, 150, 10, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Blue1.setFont(font)
        self.Blue1.setAutoFillBackground(False)
        self.Blue1.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 10px\n"
"}")
        self.Blue1.setText("")
        self.Blue1.setObjectName("Blue1")
        self.Blue2 = QtWidgets.QLabel(self.OptionsWidget)
        self.Blue2.setGeometry(QtCore.QRect(20, 210, 10, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Blue2.setFont(font)
        self.Blue2.setAutoFillBackground(False)
        self.Blue2.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 10px\n"
"}")
        self.Blue2.setText("")
        self.Blue2.setObjectName("Blue2")
        self.Blue3 = QtWidgets.QLabel(self.OptionsWidget)
        self.Blue3.setGeometry(QtCore.QRect(20, 270, 10, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Blue3.setFont(font)
        self.Blue3.setAutoFillBackground(False)
        self.Blue3.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 10px\n"
"}")
        self.Blue3.setText("")
        self.Blue3.setObjectName("Blue3")
        self.Blue4 = QtWidgets.QLabel(self.OptionsWidget)
        self.Blue4.setGeometry(QtCore.QRect(20, 330, 10, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Blue4.setFont(font)
        self.Blue4.setAutoFillBackground(False)
        self.Blue4.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 10px\n"
"}")
        self.Blue4.setText("")
        self.Blue4.setObjectName("Blue4")
        self.Blue5 = QtWidgets.QLabel(self.OptionsWidget)
        self.Blue5.setGeometry(QtCore.QRect(20, 390, 10, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Blue5.setFont(font)
        self.Blue5.setAutoFillBackground(False)
        self.Blue5.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 10px\n"
"}")
        self.Blue5.setText("")
        self.Blue5.setObjectName("Blue5")
        self.Blue6 = QtWidgets.QLabel(self.OptionsWidget)
        self.Blue6.setGeometry(QtCore.QRect(20, 450, 10, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Blue6.setFont(font)
        self.Blue6.setAutoFillBackground(False)
        self.Blue6.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 10px\n"
"}")
        self.Blue6.setText("")
        self.Blue6.setObjectName("Blue6")
        self.FunctionsStackedWidget = QtWidgets.QStackedWidget(self.CentralWidget)
        self.FunctionsStackedWidget.setGeometry(QtCore.QRect(210, -20, 731, 601))
        self.FunctionsStackedWidget.setAutoFillBackground(False)
        self.FunctionsStackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FunctionsStackedWidget.setObjectName("FunctionsStackedWidget")
        self.HomePage = QtWidgets.QWidget()
        self.HomePage.setObjectName("HomePage")
        self.Home_Label = QtWidgets.QLabel(self.HomePage)
        self.Home_Label.setGeometry(QtCore.QRect(30, 80, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Home_Label.setFont(font)
        self.Home_Label.setObjectName("Home_Label")
        self.Notice_Widget = QtWidgets.QWidget(self.HomePage)
        self.Notice_Widget.setGeometry(QtCore.QRect(30, 140, 321, 141))
        self.Notice_Widget.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.Notice_Widget.setObjectName("Notice_Widget")
        self.Notice_Label = QtWidgets.QLabel(self.Notice_Widget)
        self.Notice_Label.setGeometry(QtCore.QRect(10, 20, 281, 101))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Notice_Label.setFont(font)
        self.Notice_Label.setAutoFillBackground(False)
        self.Notice_Label.setStyleSheet("")
        self.Notice_Label.setObjectName("Notice_Label")
        self.HomeTip1_Widget = QtWidgets.QWidget(self.HomePage)
        self.HomeTip1_Widget.setGeometry(QtCore.QRect(30, 290, 321, 171))
        self.HomeTip1_Widget.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.HomeTip1_Widget.setObjectName("HomeTip1_Widget")
        self.HomeTip1_Label = QtWidgets.QLabel(self.HomeTip1_Widget)
        self.HomeTip1_Label.setGeometry(QtCore.QRect(10, 20, 281, 131))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.HomeTip1_Label.setFont(font)
        self.HomeTip1_Label.setAutoFillBackground(False)
        self.HomeTip1_Label.setStyleSheet("")
        self.HomeTip1_Label.setObjectName("HomeTip1_Label")
        self.HomePageButtons_Widget = QtWidgets.QWidget(self.HomePage)
        self.HomePageButtons_Widget.setGeometry(QtCore.QRect(470, 410, 251, 181))
        self.HomePageButtons_Widget.setObjectName("HomePageButtons_Widget")
        self.Selected_Server_Label = QtWidgets.QLabel(self.HomePageButtons_Widget)
        self.Selected_Server_Label.setGeometry(QtCore.QRect(20, 150, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.Selected_Server_Label.setFont(font)
        self.Selected_Server_Label.setObjectName("Selected_Server_Label")
        self.Start_PushButton = QtWidgets.QPushButton(self.HomePageButtons_Widget)
        self.Start_PushButton.setGeometry(QtCore.QRect(10, 80, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.Start_PushButton.setFont(font)
        self.Start_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Start_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 110, 212);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 100, 212);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Start_PushButton.setFlat(False)
        self.Start_PushButton.setObjectName("Start_PushButton")
        self.Config_PushButton = QtWidgets.QPushButton(self.HomePageButtons_Widget)
        self.Config_PushButton.setGeometry(QtCore.QRect(130, 10, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.Config_PushButton.setFont(font)
        self.Config_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Config_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 7px;\n"
"}")
        self.Config_PushButton.setObjectName("Config_PushButton")
        self.Choose_Server_PushButton = QtWidgets.QPushButton(self.HomePageButtons_Widget)
        self.Choose_Server_PushButton.setGeometry(QtCore.QRect(10, 10, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.Choose_Server_PushButton.setFont(font)
        self.Choose_Server_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Choose_Server_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 7px;\n"
"}")
        self.Choose_Server_PushButton.setObjectName("Choose_Server_PushButton")
        self.FunctionsStackedWidget.addWidget(self.HomePage)
        self.ConfigPage = QtWidgets.QWidget()
        self.ConfigPage.setObjectName("ConfigPage")
        self.Config_Label = QtWidgets.QLabel(self.ConfigPage)
        self.Config_Label.setGeometry(QtCore.QRect(30, 80, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Config_Label.setFont(font)
        self.Config_Label.setObjectName("Config_Label")
        self.Others_Background = QtWidgets.QLabel(self.ConfigPage)
        self.Others_Background.setGeometry(QtCore.QRect(30, 400, 251, 121))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Others_Background.setFont(font)
        self.Others_Background.setAutoFillBackground(False)
        self.Others_Background.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.Others_Background.setText("")
        self.Others_Background.setObjectName("Others_Background")
        self.Server_Name_Label = QtWidgets.QLabel(self.ConfigPage)
        self.Server_Name_Label.setGeometry(QtCore.QRect(50, 420, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Server_Name_Label.setFont(font)
        self.Server_Name_Label.setObjectName("Server_Name_Label")
        self.Server_Name_LineEdit = QtWidgets.QLineEdit(self.ConfigPage)
        self.Server_Name_LineEdit.setGeometry(QtCore.QRect(150, 430, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.Server_Name_LineEdit.setFont(font)
        self.Server_Name_LineEdit.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 3px;\n"
"    border: 2px;\n"
"    border-color: rgb(223, 223, 223);\n"
"    border-style: solid;\n"
"}\n"
"")
        self.Server_Name_LineEdit.setObjectName("Server_Name_LineEdit")
        self.Completed_Save_PushButton = QtWidgets.QPushButton(self.ConfigPage)
        self.Completed_Save_PushButton.setGeometry(QtCore.QRect(50, 470, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Completed_Save_PushButton.setFont(font)
        self.Completed_Save_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Completed_Save_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 110, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 100, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Completed_Save_PushButton.setFlat(False)
        self.Completed_Save_PushButton.setObjectName("Completed_Save_PushButton")
        self.ConfigTip1_Widget = QtWidgets.QWidget(self.ConfigPage)
        self.ConfigTip1_Widget.setGeometry(QtCore.QRect(30, 140, 251, 121))
        self.ConfigTip1_Widget.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.ConfigTip1_Widget.setObjectName("ConfigTip1_Widget")
        self.ConfigTip1_Label = QtWidgets.QLabel(self.ConfigTip1_Widget)
        self.ConfigTip1_Label.setGeometry(QtCore.QRect(10, 20, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.ConfigTip1_Label.setFont(font)
        self.ConfigTip1_Label.setAutoFillBackground(False)
        self.ConfigTip1_Label.setStyleSheet("")
        self.ConfigTip1_Label.setObjectName("ConfigTip1_Label")
        self.ConfigTip2_Widget = QtWidgets.QWidget(self.ConfigPage)
        self.ConfigTip2_Widget.setGeometry(QtCore.QRect(30, 280, 251, 101))
        self.ConfigTip2_Widget.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.ConfigTip2_Widget.setObjectName("ConfigTip2_Widget")
        self.ConfigTip2_Label = QtWidgets.QLabel(self.ConfigTip2_Widget)
        self.ConfigTip2_Label.setGeometry(QtCore.QRect(10, 10, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.ConfigTip2_Label.setFont(font)
        self.ConfigTip2_Label.setAutoFillBackground(False)
        self.ConfigTip2_Label.setStyleSheet("")
        self.ConfigTip2_Label.setObjectName("ConfigTip2_Label")
        self.Configuration_Widget = QtWidgets.QWidget(self.ConfigPage)
        self.Configuration_Widget.setGeometry(QtCore.QRect(310, 140, 351, 341))
        self.Configuration_Widget.setObjectName("Configuration_Widget")
        self.Download_Core_PushButton = QtWidgets.QPushButton(self.Configuration_Widget)
        self.Download_Core_PushButton.setGeometry(QtCore.QRect(230, 240, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Download_Core_PushButton.setFont(font)
        self.Download_Core_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Download_Core_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 110, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 100, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Download_Core_PushButton.setFlat(False)
        self.Download_Core_PushButton.setObjectName("Download_Core_PushButton")
        self.Download_Java_PushButton = QtWidgets.QPushButton(self.Configuration_Widget)
        self.Download_Java_PushButton.setGeometry(QtCore.QRect(130, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Download_Java_PushButton.setFont(font)
        self.Download_Java_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Download_Java_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 110, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 100, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Download_Java_PushButton.setFlat(False)
        self.Download_Java_PushButton.setObjectName("Download_Java_PushButton")
        self.Manual_Import_Core_PushButton = QtWidgets.QPushButton(self.Configuration_Widget)
        self.Manual_Import_Core_PushButton.setGeometry(QtCore.QRect(120, 240, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Manual_Import_Core_PushButton.setFont(font)
        self.Manual_Import_Core_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Manual_Import_Core_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 110, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 100, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Manual_Import_Core_PushButton.setFlat(False)
        self.Manual_Import_Core_PushButton.setObjectName("Manual_Import_Core_PushButton")
        self.Set_Core_Background = QtWidgets.QLabel(self.Configuration_Widget)
        self.Set_Core_Background.setGeometry(QtCore.QRect(0, 220, 351, 121))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Set_Core_Background.setFont(font)
        self.Set_Core_Background.setAutoFillBackground(False)
        self.Set_Core_Background.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.Set_Core_Background.setText("")
        self.Set_Core_Background.setObjectName("Set_Core_Background")
        self.Set_Java_Background = QtWidgets.QLabel(self.Configuration_Widget)
        self.Set_Java_Background.setGeometry(QtCore.QRect(0, 0, 351, 121))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Set_Java_Background.setFont(font)
        self.Set_Java_Background.setAutoFillBackground(False)
        self.Set_Java_Background.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.Set_Java_Background.setText("")
        self.Set_Java_Background.setObjectName("Set_Java_Background")
        self.Memory_1_Label = QtWidgets.QLabel(self.Configuration_Widget)
        self.Memory_1_Label.setGeometry(QtCore.QRect(20, 150, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Memory_1_Label.setFont(font)
        self.Memory_1_Label.setObjectName("Memory_1_Label")
        self.MinMemory_LineEdit = QtWidgets.QLineEdit(self.Configuration_Widget)
        self.MinMemory_LineEdit.setGeometry(QtCore.QRect(70, 160, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.MinMemory_LineEdit.setFont(font)
        self.MinMemory_LineEdit.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 3px;\n"
"    border: 2px;\n"
"    border-color: rgb(223, 223, 223);\n"
"    border-style: solid;\n"
"}\n"
"")
        self.MinMemory_LineEdit.setObjectName("MinMemory_LineEdit")
        self.Set_Memory_Background = QtWidgets.QLabel(self.Configuration_Widget)
        self.Set_Memory_Background.setGeometry(QtCore.QRect(0, 140, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Set_Memory_Background.setFont(font)
        self.Set_Memory_Background.setAutoFillBackground(False)
        self.Set_Memory_Background.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.Set_Memory_Background.setText("")
        self.Set_Memory_Background.setObjectName("Set_Memory_Background")
        self.ConfigTip3_Label = QtWidgets.QLabel(self.Configuration_Widget)
        self.ConfigTip3_Label.setGeometry(QtCore.QRect(20, 280, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.ConfigTip3_Label.setFont(font)
        self.ConfigTip3_Label.setStyleSheet("")
        self.ConfigTip3_Label.setObjectName("ConfigTip3_Label")
        self.Java_Label = QtWidgets.QLabel(self.Configuration_Widget)
        self.Java_Label.setGeometry(QtCore.QRect(20, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Java_Label.setFont(font)
        self.Java_Label.setObjectName("Java_Label")
        self.MaxMemory_LineEdit = QtWidgets.QLineEdit(self.Configuration_Widget)
        self.MaxMemory_LineEdit.setGeometry(QtCore.QRect(190, 160, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.MaxMemory_LineEdit.setFont(font)
        self.MaxMemory_LineEdit.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 3px;\n"
"    border: 2px;\n"
"    border-color: rgb(223, 223, 223);\n"
"    border-style: solid;\n"
"}\n"
"")
        self.MaxMemory_LineEdit.setObjectName("MaxMemory_LineEdit")
        self.Memory_2_Label = QtWidgets.QLabel(self.Configuration_Widget)
        self.Memory_2_Label.setGeometry(QtCore.QRect(170, 150, 21, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.Memory_2_Label.setFont(font)
        self.Memory_2_Label.setObjectName("Memory_2_Label")
        self.Core_Label = QtWidgets.QLabel(self.Configuration_Widget)
        self.Core_Label.setGeometry(QtCore.QRect(20, 240, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Core_Label.setFont(font)
        self.Core_Label.setObjectName("Core_Label")
        self.Auto_Find_Java_PushButton = QtWidgets.QPushButton(self.Configuration_Widget)
        self.Auto_Find_Java_PushButton.setGeometry(QtCore.QRect(20, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Auto_Find_Java_PushButton.setFont(font)
        self.Auto_Find_Java_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Auto_Find_Java_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 110, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 100, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Auto_Find_Java_PushButton.setFlat(False)
        self.Auto_Find_Java_PushButton.setObjectName("Auto_Find_Java_PushButton")
        self.Memory_Unit_Label = QtWidgets.QLabel(self.Configuration_Widget)
        self.Memory_Unit_Label.setGeometry(QtCore.QRect(290, 150, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Memory_Unit_Label.setFont(font)
        self.Memory_Unit_Label.setObjectName("Memory_Unit_Label")
        self.Java_Version_Label = QtWidgets.QLabel(self.Configuration_Widget)
        self.Java_Version_Label.setGeometry(QtCore.QRect(80, 20, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Java_Version_Label.setFont(font)
        self.Java_Version_Label.setText("")
        self.Java_Version_Label.setObjectName("Java_Version_Label")
        self.Founded_Java_List_PushButton = QtWidgets.QPushButton(self.Configuration_Widget)
        self.Founded_Java_List_PushButton.setGeometry(QtCore.QRect(240, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Founded_Java_List_PushButton.setFont(font)
        self.Founded_Java_List_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Founded_Java_List_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(227, 227, 227);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 7px;\n"
"}")
        self.Founded_Java_List_PushButton.setObjectName("Founded_Java_List_PushButton")
        self.Set_Core_Background.raise_()
        self.Set_Memory_Background.raise_()
        self.Set_Java_Background.raise_()
        self.Download_Core_PushButton.raise_()
        self.Download_Java_PushButton.raise_()
        self.Manual_Import_Core_PushButton.raise_()
        self.Memory_1_Label.raise_()
        self.MinMemory_LineEdit.raise_()
        self.ConfigTip3_Label.raise_()
        self.Java_Label.raise_()
        self.MaxMemory_LineEdit.raise_()
        self.Memory_2_Label.raise_()
        self.Core_Label.raise_()
        self.Auto_Find_Java_PushButton.raise_()
        self.Memory_Unit_Label.raise_()
        self.Java_Version_Label.raise_()
        self.Founded_Java_List_PushButton.raise_()
        self.FunctionsStackedWidget.addWidget(self.ConfigPage)
        self.DownloadPage = QtWidgets.QWidget()
        self.DownloadPage.setObjectName("DownloadPage")
        self.Download_Label = QtWidgets.QLabel(self.DownloadPage)
        self.Download_Label.setGeometry(QtCore.QRect(30, 80, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Download_Label.setFont(font)
        self.Download_Label.setObjectName("Download_Label")
        self.Download_Source_Background = QtWidgets.QLabel(self.DownloadPage)
        self.Download_Source_Background.setGeometry(QtCore.QRect(250, 60, 431, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Download_Source_Background.setFont(font)
        self.Download_Source_Background.setAutoFillBackground(False)
        self.Download_Source_Background.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.Download_Source_Background.setText("")
        self.Download_Source_Background.setObjectName("Download_Source_Background")
        self.Download_Source_Label = QtWidgets.QLabel(self.DownloadPage)
        self.Download_Source_Label.setGeometry(QtCore.QRect(270, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.Download_Source_Label.setFont(font)
        self.Download_Source_Label.setObjectName("Download_Source_Label")
        self.luoxisCloud_radioButton = QtWidgets.QRadioButton(self.DownloadPage)
        self.luoxisCloud_radioButton.setGeometry(QtCore.QRect(560, 70, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.luoxisCloud_radioButton.setFont(font)
        self.luoxisCloud_radioButton.setObjectName("luoxisCloud_radioButton")
        self.Gitee_radioButton = QtWidgets.QRadioButton(self.DownloadPage)
        self.Gitee_radioButton.setGeometry(QtCore.QRect(460, 70, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Gitee_radioButton.setFont(font)
        self.Gitee_radioButton.setObjectName("Gitee_radioButton")
        self.SharePoint_radioButton = QtWidgets.QRadioButton(self.DownloadPage)
        self.SharePoint_radioButton.setGeometry(QtCore.QRect(350, 70, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.SharePoint_radioButton.setFont(font)
        self.SharePoint_radioButton.setChecked(True)
        self.SharePoint_radioButton.setObjectName("SharePoint_radioButton")
        self.GitHub_radioButton = QtWidgets.QRadioButton(self.DownloadPage)
        self.GitHub_radioButton.setGeometry(QtCore.QRect(460, 100, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.GitHub_radioButton.setFont(font)
        self.GitHub_radioButton.setObjectName("GitHub_radioButton")
        self.GHProxy_radioButton = QtWidgets.QRadioButton(self.DownloadPage)
        self.GHProxy_radioButton.setGeometry(QtCore.QRect(350, 100, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.GHProxy_radioButton.setFont(font)
        self.GHProxy_radioButton.setObjectName("GHProxy_radioButton")
        self.DownloadSwitcher_TabWidget = QtWidgets.QTabWidget(self.DownloadPage)
        self.DownloadSwitcher_TabWidget.setGeometry(QtCore.QRect(30, 150, 651, 411))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.DownloadSwitcher_TabWidget.setFont(font)
        self.DownloadSwitcher_TabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.DownloadSwitcher_TabWidget.setStyleSheet("QTabWidget\n"
"{\n"
"    background-color:rgb(247, 247, 247);\n"
"}\n"
"QTabWidget::pane\n"
"{\n"
"    background-color: rgb(235, 235, 235);\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"    border:none;\n"
"}\n"
"QTabBar::tab\n"
"{\n"
"    background-color:rgb(247, 247, 247);\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    min-width: 100px;\n"
"    min-height: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    background-color: rgb(235, 235, 235);\n"
"}")
        self.DownloadSwitcher_TabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.DownloadSwitcher_TabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.DownloadSwitcher_TabWidget.setUsesScrollButtons(False)
        self.DownloadSwitcher_TabWidget.setObjectName("DownloadSwitcher_TabWidget")
        self.JavaTab = QtWidgets.QWidget()
        self.JavaTab.setObjectName("JavaTab")
        self.JavaScrollArea = QtWidgets.QScrollArea(self.JavaTab)
        self.JavaScrollArea.setGeometry(QtCore.QRect(10, 10, 631, 351))
        self.JavaScrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.JavaScrollArea.setStyleSheet("QScrollArea{\n"
"    border: 0px solid;\n"
"    border-right-color: #dcdbdc;\n"
"    background-color: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 12px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(220, 220, 220);\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::add-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::up-arrow:vertial,QScrollBar::down-arrow:vertial\n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.JavaScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.JavaScrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.JavaScrollArea.setLineWidth(0)
        self.JavaScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.JavaScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.JavaScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.JavaScrollArea.setWidgetResizable(True)
        self.JavaScrollArea.setObjectName("JavaScrollArea")
        self.JavaScrollAreaWidgetContents = QtWidgets.QWidget()
        self.JavaScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 619, 351))
        self.JavaScrollAreaWidgetContents.setObjectName("JavaScrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.JavaScrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.JavaVerticalLayout = QtWidgets.QVBoxLayout()
        self.JavaVerticalLayout.setObjectName("JavaVerticalLayout")
        self.verticalLayout_2.addLayout(self.JavaVerticalLayout)
        self.JavaScrollArea.setWidget(self.JavaScrollAreaWidgetContents)
        self.DownloadSwitcher_TabWidget.addTab(self.JavaTab, "")
        self.SpigotTab = QtWidgets.QWidget()
        self.SpigotTab.setObjectName("SpigotTab")
        self.SpigotScrollArea = QtWidgets.QScrollArea(self.SpigotTab)
        self.SpigotScrollArea.setGeometry(QtCore.QRect(10, 10, 631, 351))
        self.SpigotScrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.SpigotScrollArea.setStyleSheet("QScrollArea{\n"
"    border: 0px solid;\n"
"    border-right-color: #dcdbdc;\n"
"    background-color: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 12px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(220, 220, 220);\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::add-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::up-arrow:vertial,QScrollBar::down-arrow:vertial\n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.SpigotScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SpigotScrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SpigotScrollArea.setLineWidth(0)
        self.SpigotScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.SpigotScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SpigotScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.SpigotScrollArea.setWidgetResizable(True)
        self.SpigotScrollArea.setObjectName("SpigotScrollArea")
        self.SpigotScrollAreaWidgetContents = QtWidgets.QWidget()
        self.SpigotScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 619, 351))
        self.SpigotScrollAreaWidgetContents.setObjectName("SpigotScrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.SpigotScrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SpigotVerticalLayout = QtWidgets.QVBoxLayout()
        self.SpigotVerticalLayout.setObjectName("SpigotVerticalLayout")
        self.verticalLayout.addLayout(self.SpigotVerticalLayout)
        self.SpigotScrollArea.setWidget(self.SpigotScrollAreaWidgetContents)
        self.DownloadSwitcher_TabWidget.addTab(self.SpigotTab, "")
        self.PaperTab = QtWidgets.QWidget()
        self.PaperTab.setObjectName("PaperTab")
        self.PaperScrollArea = QtWidgets.QScrollArea(self.PaperTab)
        self.PaperScrollArea.setGeometry(QtCore.QRect(10, 10, 631, 351))
        self.PaperScrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.PaperScrollArea.setStyleSheet("QScrollArea{\n"
"    border: 0px solid;\n"
"    border-right-color: #dcdbdc;\n"
"    background-color: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 12px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(220, 220, 220);\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::add-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::up-arrow:vertial,QScrollBar::down-arrow:vertial\n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.PaperScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PaperScrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.PaperScrollArea.setLineWidth(0)
        self.PaperScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.PaperScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.PaperScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.PaperScrollArea.setWidgetResizable(True)
        self.PaperScrollArea.setObjectName("PaperScrollArea")
        self.PaperScrollAreaWidgetContents = QtWidgets.QWidget()
        self.PaperScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 619, 351))
        self.PaperScrollAreaWidgetContents.setObjectName("PaperScrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.PaperScrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PaperVerticalLayout = QtWidgets.QVBoxLayout()
        self.PaperVerticalLayout.setObjectName("PaperVerticalLayout")
        self.verticalLayout_3.addLayout(self.PaperVerticalLayout)
        self.PaperScrollArea.setWidget(self.PaperScrollAreaWidgetContents)
        self.DownloadSwitcher_TabWidget.addTab(self.PaperTab, "")
        self.BungeeCordTab = QtWidgets.QWidget()
        self.BungeeCordTab.setObjectName("BungeeCordTab")
        self.BungeeCordScrollArea = QtWidgets.QScrollArea(self.BungeeCordTab)
        self.BungeeCordScrollArea.setGeometry(QtCore.QRect(10, 10, 631, 351))
        self.BungeeCordScrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.BungeeCordScrollArea.setStyleSheet("QScrollArea{\n"
"    border: 0px solid;\n"
"    border-right-color: #dcdbdc;\n"
"    background-color: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 12px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(220, 220, 220);\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::add-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::up-arrow:vertial,QScrollBar::down-arrow:vertial\n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.BungeeCordScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BungeeCordScrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.BungeeCordScrollArea.setLineWidth(0)
        self.BungeeCordScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.BungeeCordScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.BungeeCordScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.BungeeCordScrollArea.setWidgetResizable(True)
        self.BungeeCordScrollArea.setObjectName("BungeeCordScrollArea")
        self.BungeeCordScrollAreaWidgetContents = QtWidgets.QWidget()
        self.BungeeCordScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 619, 351))
        self.BungeeCordScrollAreaWidgetContents.setObjectName("BungeeCordScrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.BungeeCordScrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BCVerticalLayout = QtWidgets.QVBoxLayout()
        self.BCVerticalLayout.setObjectName("BCVerticalLayout")
        self.verticalLayout_4.addLayout(self.BCVerticalLayout)
        self.BungeeCordScrollArea.setWidget(self.BungeeCordScrollAreaWidgetContents)
        self.DownloadSwitcher_TabWidget.addTab(self.BungeeCordTab, "")
        self.OfficialCoreTab = QtWidgets.QWidget()
        self.OfficialCoreTab.setObjectName("OfficialCoreTab")
        self.OfficialCoreScrollArea = QtWidgets.QScrollArea(self.OfficialCoreTab)
        self.OfficialCoreScrollArea.setGeometry(QtCore.QRect(10, 10, 631, 351))
        self.OfficialCoreScrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.OfficialCoreScrollArea.setStyleSheet("QScrollArea{\n"
"    border: 0px solid;\n"
"    border-right-color: #dcdbdc;\n"
"    background-color: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 12px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(220, 220, 220);\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::add-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::up-arrow:vertial,QScrollBar::down-arrow:vertial\n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.OfficialCoreScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.OfficialCoreScrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.OfficialCoreScrollArea.setLineWidth(0)
        self.OfficialCoreScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.OfficialCoreScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.OfficialCoreScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.OfficialCoreScrollArea.setWidgetResizable(True)
        self.OfficialCoreScrollArea.setObjectName("OfficialCoreScrollArea")
        self.OfficialCoreScrollAreaWidgetContents = QtWidgets.QWidget()
        self.OfficialCoreScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 619, 351))
        self.OfficialCoreScrollAreaWidgetContents.setObjectName("OfficialCoreScrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.OfficialCoreScrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.OfficialCoreVerticalLayout = QtWidgets.QVBoxLayout()
        self.OfficialCoreVerticalLayout.setObjectName("OfficialCoreVerticalLayout")
        self.verticalLayout_5.addLayout(self.OfficialCoreVerticalLayout)
        self.OfficialCoreScrollArea.setWidget(self.OfficialCoreScrollAreaWidgetContents)
        self.DownloadSwitcher_TabWidget.addTab(self.OfficialCoreTab, "")
        self.More_Download_PushButton = QtWidgets.QPushButton(self.DownloadPage)
        self.More_Download_PushButton.setGeometry(QtCore.QRect(640, 140, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.More_Download_PushButton.setFont(font)
        self.More_Download_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.More_Download_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(227, 227, 227);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 7px;\n"
"}")
        self.More_Download_PushButton.setObjectName("More_Download_PushButton")
        self.FunctionsStackedWidget.addWidget(self.DownloadPage)
        self.ConsolePage = QtWidgets.QWidget()
        self.ConsolePage.setObjectName("ConsolePage")
        self.Console_Label = QtWidgets.QLabel(self.ConsolePage)
        self.Console_Label.setGeometry(QtCore.QRect(30, 80, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Console_Label.setFont(font)
        self.Console_Label.setObjectName("Console_Label")
        self.Console_Background = QtWidgets.QLabel(self.ConsolePage)
        self.Console_Background.setGeometry(QtCore.QRect(30, 140, 651, 311))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Console_Background.setFont(font)
        self.Console_Background.setAutoFillBackground(False)
        self.Console_Background.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.Console_Background.setText("")
        self.Console_Background.setObjectName("Console_Background")
        self.Command_Background = QtWidgets.QLabel(self.ConsolePage)
        self.Command_Background.setGeometry(QtCore.QRect(30, 470, 651, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Command_Background.setFont(font)
        self.Command_Background.setAutoFillBackground(False)
        self.Command_Background.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.Command_Background.setObjectName("Command_Background")
        self.Send_Command_PushButton = QtWidgets.QPushButton(self.ConsolePage)
        self.Send_Command_PushButton.setGeometry(QtCore.QRect(570, 480, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Send_Command_PushButton.setFont(font)
        self.Send_Command_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Send_Command_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 110, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 100, 212);\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Send_Command_PushButton.setFlat(False)
        self.Send_Command_PushButton.setObjectName("Send_Command_PushButton")
        self.Command_LineEdit = QtWidgets.QLineEdit(self.ConsolePage)
        self.Command_LineEdit.setGeometry(QtCore.QRect(70, 480, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.Command_LineEdit.setFont(font)
        self.Command_LineEdit.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 3px;\n"
"}\n"
"")
        self.Command_LineEdit.setObjectName("Command_LineEdit")
        self.FunctionsStackedWidget.addWidget(self.ConsolePage)
        self.ToolsPage = QtWidgets.QWidget()
        self.ToolsPage.setObjectName("ToolsPage")
        self.Tools_Label = QtWidgets.QLabel(self.ToolsPage)
        self.Tools_Label.setGeometry(QtCore.QRect(30, 80, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Tools_Label.setFont(font)
        self.Tools_Label.setObjectName("Tools_Label")
        self.FunctionsStackedWidget.addWidget(self.ToolsPage)
        self.AboutPage = QtWidgets.QWidget()
        self.AboutPage.setObjectName("AboutPage")
        self.About_Label = QtWidgets.QLabel(self.AboutPage)
        self.About_Label.setGeometry(QtCore.QRect(30, 80, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.About_Label.setFont(font)
        self.About_Label.setObjectName("About_Label")
        self.About_Background = QtWidgets.QLabel(self.AboutPage)
        self.About_Background.setGeometry(QtCore.QRect(30, 140, 261, 231))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.About_Background.setFont(font)
        self.About_Background.setAutoFillBackground(False)
        self.About_Background.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.About_Background.setText("")
        self.About_Background.setObjectName("About_Background")
        self.MCSL2_Icon_Label = QtWidgets.QLabel(self.AboutPage)
        self.MCSL2_Icon_Label.setGeometry(QtCore.QRect(60, 170, 71, 71))
        self.MCSL2_Icon_Label.setText("")
        self.MCSL2_Icon_Label.setPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Icon.png"))
        self.MCSL2_Icon_Label.setScaledContents(True)
        self.MCSL2_Icon_Label.setObjectName("MCSL2_Icon_Label")
        self.MCSL2_Label = QtWidgets.QLabel(self.AboutPage)
        self.MCSL2_Label.setGeometry(QtCore.QRect(150, 180, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.MCSL2_Label.setFont(font)
        self.MCSL2_Label.setObjectName("MCSL2_Label")
        self.MCSL2_Author_Label_1 = QtWidgets.QLabel(self.AboutPage)
        self.MCSL2_Author_Label_1.setGeometry(QtCore.QRect(150, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.MCSL2_Author_Label_1.setFont(font)
        self.MCSL2_Author_Label_1.setObjectName("MCSL2_Author_Label_1")
        self.MCSL2_Author_Avatar = QtWidgets.QLabel(self.AboutPage)
        self.MCSL2_Author_Avatar.setGeometry(QtCore.QRect(60, 270, 71, 71))
        self.MCSL2_Author_Avatar.setText("")
        self.MCSL2_Author_Avatar.setPixmap(QtGui.QPixmap(":/MCSL2_Icon/MCSL2_Author.png"))
        self.MCSL2_Author_Avatar.setScaledContents(True)
        self.MCSL2_Author_Avatar.setObjectName("MCSL2_Author_Avatar")
        self.MCSL2_Author_Label_2 = QtWidgets.QLabel(self.AboutPage)
        self.MCSL2_Author_Label_2.setGeometry(QtCore.QRect(150, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.MCSL2_Author_Label_2.setFont(font)
        self.MCSL2_Author_Label_2.setObjectName("MCSL2_Author_Label_2")
        self.Description_Label = QtWidgets.QLabel(self.AboutPage)
        self.Description_Label.setGeometry(QtCore.QRect(310, 140, 381, 311))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.Description_Label.setFont(font)
        self.Description_Label.setAutoFillBackground(False)
        self.Description_Label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.Description_Label.setObjectName("Description_Label")
        self.Check_Update_PushButton = QtWidgets.QPushButton(self.AboutPage)
        self.Check_Update_PushButton.setGeometry(QtCore.QRect(30, 390, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        self.Check_Update_PushButton.setFont(font)
        self.Check_Update_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Check_Update_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 7px;\n"
"}")
        self.Check_Update_PushButton.setObjectName("Check_Update_PushButton")
        self.FunctionsStackedWidget.addWidget(self.AboutPage)
        self.ChooseServerPage = QtWidgets.QWidget()
        self.ChooseServerPage.setObjectName("ChooseServerPage")
        self.Choose_Server_Label = QtWidgets.QLabel(self.ChooseServerPage)
        self.Choose_Server_Label.setGeometry(QtCore.QRect(30, 80, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Choose_Server_Label.setFont(font)
        self.Choose_Server_Label.setObjectName("Choose_Server_Label")
        self.Completed_Choose_Server_PushButton = QtWidgets.QPushButton(self.ChooseServerPage)
        self.Completed_Choose_Server_PushButton.setGeometry(QtCore.QRect(560, 510, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.Completed_Choose_Server_PushButton.setFont(font)
        self.Completed_Choose_Server_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Completed_Choose_Server_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 107, 212);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Completed_Choose_Server_PushButton.setFlat(False)
        self.Completed_Choose_Server_PushButton.setObjectName("Completed_Choose_Server_PushButton")
        self.Choose_Server_Tip1_Widget = QtWidgets.QWidget(self.ChooseServerPage)
        self.Choose_Server_Tip1_Widget.setGeometry(QtCore.QRect(30, 140, 651, 81))
        self.Choose_Server_Tip1_Widget.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.Choose_Server_Tip1_Widget.setObjectName("Choose_Server_Tip1_Widget")
        self.Choose_Server_Tip1_Label = QtWidgets.QLabel(self.Choose_Server_Tip1_Widget)
        self.Choose_Server_Tip1_Label.setGeometry(QtCore.QRect(20, 0, 601, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Choose_Server_Tip1_Label.setFont(font)
        self.Choose_Server_Tip1_Label.setAutoFillBackground(False)
        self.Choose_Server_Tip1_Label.setStyleSheet("")
        self.Choose_Server_Tip1_Label.setObjectName("Choose_Server_Tip1_Label")
        self.ChooseServerScrollArea = QtWidgets.QScrollArea(self.ChooseServerPage)
        self.ChooseServerScrollArea.setGeometry(QtCore.QRect(30, 240, 651, 251))
        self.ChooseServerScrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ChooseServerScrollArea.setStyleSheet("QScrollArea{\n"
"    border: 0px solid;\n"
"    border-right-color: #dcdbdc;\n"
"    background-color: rgb(230, 230, 230);\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 12px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(220, 220, 220);\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::add-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::up-arrow:vertial,QScrollBar::down-arrow:vertial\n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.ChooseServerScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ChooseServerScrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ChooseServerScrollArea.setLineWidth(0)
        self.ChooseServerScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ChooseServerScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ChooseServerScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.ChooseServerScrollArea.setWidgetResizable(True)
        self.ChooseServerScrollArea.setObjectName("ChooseServerScrollArea")
        self.ChooseServerScrollAreaWidgetContents = QtWidgets.QWidget()
        self.ChooseServerScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 639, 251))
        self.ChooseServerScrollAreaWidgetContents.setObjectName("ChooseServerScrollAreaWidgetContents")
        self.ChooseServerScrollArea.setWidget(self.ChooseServerScrollAreaWidgetContents)
        self.FunctionsStackedWidget.addWidget(self.ChooseServerPage)
        self.ChooseJavaPage = QtWidgets.QWidget()
        self.ChooseJavaPage.setObjectName("ChooseJavaPage")
        self.Choose_Java_Label = QtWidgets.QLabel(self.ChooseJavaPage)
        self.Choose_Java_Label.setGeometry(QtCore.QRect(30, 80, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Choose_Java_Label.setFont(font)
        self.Choose_Java_Label.setObjectName("Choose_Java_Label")
        self.Completed_Choose_Java_PushButton = QtWidgets.QPushButton(self.ChooseJavaPage)
        self.Completed_Choose_Java_PushButton.setGeometry(QtCore.QRect(560, 490, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.Completed_Choose_Java_PushButton.setFont(font)
        self.Completed_Choose_Java_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Completed_Choose_Java_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 107, 212);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Completed_Choose_Java_PushButton.setFlat(False)
        self.Completed_Choose_Java_PushButton.setObjectName("Completed_Choose_Java_PushButton")
        self.ChooseJavaScrollArea = QtWidgets.QScrollArea(self.ChooseJavaPage)
        self.ChooseJavaScrollArea.setGeometry(QtCore.QRect(40, 150, 641, 321))
        self.ChooseJavaScrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ChooseJavaScrollArea.setStyleSheet("QScrollArea{\n"
"    border: 0px solid;\n"
"    border-right-color: #dcdbdc;\n"
"    background-color: rgb(230, 230, 230);\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 12px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(220, 220, 220);\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::add-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertial \n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::up-arrow:vertial,QScrollBar::down-arrow:vertial\n"
"{    \n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.ChooseJavaScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ChooseJavaScrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ChooseJavaScrollArea.setLineWidth(0)
        self.ChooseJavaScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ChooseJavaScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ChooseJavaScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.ChooseJavaScrollArea.setWidgetResizable(True)
        self.ChooseJavaScrollArea.setObjectName("ChooseJavaScrollArea")
        self.ChooseJavaScrollAreaWidgetContents = QtWidgets.QWidget()
        self.ChooseJavaScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 629, 321))
        self.ChooseJavaScrollAreaWidgetContents.setObjectName("ChooseJavaScrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ChooseJavaScrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ChooseJavaScrollAreaVerticalLayout = QtWidgets.QVBoxLayout()
        self.ChooseJavaScrollAreaVerticalLayout.setObjectName("ChooseJavaScrollAreaVerticalLayout")
        self.verticalLayout_6.addLayout(self.ChooseJavaScrollAreaVerticalLayout)
        self.ChooseJavaScrollArea.setWidget(self.ChooseJavaScrollAreaWidgetContents)
        self.FunctionsStackedWidget.addWidget(self.ChooseJavaPage)
        self.UpdatePage = QtWidgets.QWidget()
        self.UpdatePage.setObjectName("UpdatePage")
        self.Update_Label = QtWidgets.QLabel(self.UpdatePage)
        self.Update_Label.setGeometry(QtCore.QRect(30, 80, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Update_Label.setFont(font)
        self.Update_Label.setObjectName("Update_Label")
        self.Update_Tip1_Widget = QtWidgets.QWidget(self.UpdatePage)
        self.Update_Tip1_Widget.setGeometry(QtCore.QRect(30, 140, 651, 81))
        self.Update_Tip1_Widget.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.Update_Tip1_Widget.setObjectName("Update_Tip1_Widget")
        self.Update_Tip1_Label = QtWidgets.QLabel(self.Update_Tip1_Widget)
        self.Update_Tip1_Label.setGeometry(QtCore.QRect(20, 10, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Update_Tip1_Label.setFont(font)
        self.Update_Tip1_Label.setAutoFillBackground(False)
        self.Update_Tip1_Label.setStyleSheet("")
        self.Update_Tip1_Label.setObjectName("Update_Tip1_Label")
        self.DoNotUpdate_PushButton = QtWidgets.QPushButton(self.UpdatePage)
        self.DoNotUpdate_PushButton.setGeometry(QtCore.QRect(340, 490, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.DoNotUpdate_PushButton.setFont(font)
        self.DoNotUpdate_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DoNotUpdate_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 7px;\n"
"}")
        self.DoNotUpdate_PushButton.setObjectName("DoNotUpdate_PushButton")
        self.Update_PushButton = QtWidgets.QPushButton(self.UpdatePage)
        self.Update_PushButton.setGeometry(QtCore.QRect(450, 490, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.Update_PushButton.setFont(font)
        self.Update_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Update_PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(0, 120, 212);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 110, 212);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 100, 212);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Update_PushButton.setFlat(False)
        self.Update_PushButton.setObjectName("Update_PushButton")
        self.Update_Introduction_Widget = QtWidgets.QWidget(self.UpdatePage)
        self.Update_Introduction_Widget.setGeometry(QtCore.QRect(30, 230, 651, 221))
        self.Update_Introduction_Widget.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(247, 247, 247);\n"
"    border-radius: 10px\n"
"}")
        self.Update_Introduction_Widget.setObjectName("Update_Introduction_Widget")
        self.Update_Introduction_Title_Label = QtWidgets.QLabel(self.Update_Introduction_Widget)
        self.Update_Introduction_Title_Label.setGeometry(QtCore.QRect(20, 20, 601, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Update_Introduction_Title_Label.setFont(font)
        self.Update_Introduction_Title_Label.setAutoFillBackground(False)
        self.Update_Introduction_Title_Label.setStyleSheet("")
        self.Update_Introduction_Title_Label.setObjectName("Update_Introduction_Title_Label")
        self.Update_Introduction_Label = QtWidgets.QLabel(self.Update_Introduction_Widget)
        self.Update_Introduction_Label.setGeometry(QtCore.QRect(20, 60, 601, 141))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Update_Introduction_Label.setFont(font)
        self.Update_Introduction_Label.setAutoFillBackground(False)
        self.Update_Introduction_Label.setStyleSheet("")
        self.Update_Introduction_Label.setText("")
        self.Update_Introduction_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Update_Introduction_Label.setObjectName("Update_Introduction_Label")
        self.FunctionsStackedWidget.addWidget(self.UpdatePage)
        self.Background = QtWidgets.QLabel(self.CentralWidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 211, 581))
        self.Background.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px\n"
"}")
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.Background_2 = QtWidgets.QLabel(self.CentralWidget)
        self.Background_2.setGeometry(QtCore.QRect(120, 0, 821, 581))
        self.Background_2.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgba(255, 255, 255,85%);\n"
"    border-radius: 10px\n"
"}")
        self.Background_2.setText("")
        self.Background_2.setObjectName("Background_2")
        self.Background_2.raise_()
        self.Background.raise_()
        self.OptionsWidget.raise_()
        self.FunctionsStackedWidget.raise_()
        MCSL2_MainWindow.setCentralWidget(self.CentralWidget)

        self.retranslateUi(MCSL2_MainWindow)
        self.FunctionsStackedWidget.setCurrentIndex(0)
        self.DownloadSwitcher_TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MCSL2_MainWindow)

    def retranslateUi(self, MCSL2_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MCSL2_MainWindow.setWindowTitle(_translate("MCSL2_MainWindow", "MCSL 2"))
        self.Home_Page_PushButton.setText(_translate("MCSL2_MainWindow", "主页"))
        self.Config_Page_PushButton.setText(_translate("MCSL2_MainWindow", "配置服务器"))
        self.MCSL2_Title_Label.setText(_translate("MCSL2_MainWindow", "MCSL 2"))
        self.MCSL2_Title_Author_Label.setText(_translate("MCSL2_MainWindow", "by LxHTT"))
        self.Download_Page_PushButton.setText(_translate("MCSL2_MainWindow", "下载"))
        self.Server_Console_Page_PushButton.setText(_translate("MCSL2_MainWindow", "服务器控制台"))
        self.Tools_Page_PushButton.setText(_translate("MCSL2_MainWindow", "更多工具"))
        self.About_Page_PushButton.setText(_translate("MCSL2_MainWindow", "关于"))
        self.Home_Label.setText(_translate("MCSL2_MainWindow", "主页"))
        self.Notice_Label.setText(_translate("MCSL2_MainWindow", "正在获取公告..."))
        self.HomeTip1_Label.setText(_translate("MCSL2_MainWindow", "如何搭建一个Java版Minecraft服务器？\n"
"1.准备好Java、核心、电脑\n"
"（提示：可使用本程序下载）\n"
"2.配置参数（本程序“配置服务器”页）\n"
"3. 开启服务器。将服务器IP告诉玩家。"))
        self.Selected_Server_Label.setText(_translate("MCSL2_MainWindow", "未选择服务器！"))
        self.Start_PushButton.setText(_translate("MCSL2_MainWindow", "启动服务器"))
        self.Config_PushButton.setText(_translate("MCSL2_MainWindow", "配置"))
        self.Choose_Server_PushButton.setText(_translate("MCSL2_MainWindow", "选择"))
        self.Config_Label.setText(_translate("MCSL2_MainWindow", "配置服务器"))
        self.Server_Name_Label.setText(_translate("MCSL2_MainWindow", "服务器名称："))
        self.Completed_Save_PushButton.setText(_translate("MCSL2_MainWindow", "保存"))
        self.ConfigTip1_Label.setText(_translate("MCSL2_MainWindow", "一个服务器最基础的三个部件\n"
"1.存放的文件夹路径\n"
"2.服务器核心\n"
"3.Java路径"))
        self.ConfigTip2_Label.setText(_translate("MCSL2_MainWindow", "MCSL 2将会在程序目录生成\n"
"以服务器名称命名的文件夹\n"
"以存储服务器文件。"))
        self.Download_Core_PushButton.setText(_translate("MCSL2_MainWindow", "下载核心"))
        self.Download_Java_PushButton.setText(_translate("MCSL2_MainWindow", "下载Java"))
        self.Manual_Import_Core_PushButton.setText(_translate("MCSL2_MainWindow", "手动导入"))
        self.Memory_1_Label.setText(_translate("MCSL2_MainWindow", "内存："))
        self.ConfigTip3_Label.setText(_translate("MCSL2_MainWindow", "MCSL 2会把核心复制到文件夹中。当然，\n"
"你也可以自己复制，并重命名为server.jar。"))
        self.Java_Label.setText(_translate("MCSL2_MainWindow", "Java:"))
        self.Memory_2_Label.setText(_translate("MCSL2_MainWindow", "~"))
        self.Core_Label.setText(_translate("MCSL2_MainWindow", "服务器核心："))
        self.Auto_Find_Java_PushButton.setText(_translate("MCSL2_MainWindow", "自动查找"))
        self.Memory_Unit_Label.setText(_translate("MCSL2_MainWindow", "MB"))
        self.Founded_Java_List_PushButton.setText(_translate("MCSL2_MainWindow", "Java列表"))
        self.Download_Label.setText(_translate("MCSL2_MainWindow", "下载"))
        self.Download_Source_Label.setText(_translate("MCSL2_MainWindow", "下载源："))
        self.luoxisCloud_radioButton.setText(_translate("MCSL2_MainWindow", "luoxis云"))
        self.Gitee_radioButton.setText(_translate("MCSL2_MainWindow", "Gitee"))
        self.SharePoint_radioButton.setText(_translate("MCSL2_MainWindow", "SharePoint"))
        self.GitHub_radioButton.setText(_translate("MCSL2_MainWindow", "GitHub"))
        self.GHProxy_radioButton.setText(_translate("MCSL2_MainWindow", "GHProxy"))
        self.DownloadSwitcher_TabWidget.setTabText(self.DownloadSwitcher_TabWidget.indexOf(self.JavaTab), _translate("MCSL2_MainWindow", "[ 运行环境 ] Java"))
        self.DownloadSwitcher_TabWidget.setTabText(self.DownloadSwitcher_TabWidget.indexOf(self.SpigotTab), _translate("MCSL2_MainWindow", "[ 核心 ] Spigot"))
        self.DownloadSwitcher_TabWidget.setTabText(self.DownloadSwitcher_TabWidget.indexOf(self.PaperTab), _translate("MCSL2_MainWindow", "[ 核心 ] Paper"))
        self.DownloadSwitcher_TabWidget.setTabText(self.DownloadSwitcher_TabWidget.indexOf(self.BungeeCordTab), _translate("MCSL2_MainWindow", "[ 核心 ] BungeeCord"))
        self.DownloadSwitcher_TabWidget.setTabText(self.DownloadSwitcher_TabWidget.indexOf(self.OfficialCoreTab), _translate("MCSL2_MainWindow", "[ 核心 ] 官方"))
        self.More_Download_PushButton.setText(_translate("MCSL2_MainWindow", "更多"))
        self.Console_Label.setText(_translate("MCSL2_MainWindow", "服务器控制台"))
        self.Command_Background.setText(_translate("MCSL2_MainWindow", "  >"))
        self.Send_Command_PushButton.setText(_translate("MCSL2_MainWindow", "发送"))
        self.Tools_Label.setText(_translate("MCSL2_MainWindow", "更多工具"))
        self.About_Label.setText(_translate("MCSL2_MainWindow", "关于"))
        self.MCSL2_Label.setText(_translate("MCSL2_MainWindow", "MCSL 2"))
        self.MCSL2_Author_Label_1.setText(_translate("MCSL2_MainWindow", "by LxHTT"))
        self.MCSL2_Author_Label_2.setText(_translate("MCSL2_MainWindow", "Bilibili：\n"
"落雪无痕LxHTT"))
        self.Description_Label.setText(_translate("MCSL2_MainWindow", "    这是对MCSL的Remake。 \n"
"\n"
"    本来使用C#开发，但由于知识有限，无奈继续\n"
"\n"
"    使用Python。 \n"
"\n"
"    MCSL 2 重构UI，使用更加清晰的代码逻辑开发，\n"
"\n"
"    除了启动、配置、下载以外，添加了诸多拓展工具。 \n"
"\n"
"    遇到Bug，请积极反馈，以帮助改进MCSL 2。 \n"
"\n"
"    作者邮箱: lxhtz.dl@qq.com "))
        self.Check_Update_PushButton.setText(_translate("MCSL2_MainWindow", "检查更新"))
        self.Choose_Server_Label.setText(_translate("MCSL2_MainWindow", "选择服务器"))
        self.Completed_Choose_Server_PushButton.setText(_translate("MCSL2_MainWindow", "选好了"))
        self.Choose_Server_Tip1_Label.setText(_translate("MCSL2_MainWindow", "MCSL 2存放服务器数据的路径位于MCSL 2根目录以服务器名称命名的文件夹。\n"
"MCSL 2将会读取目录下的文件夹名称以确定一个服务器。"))
        self.Choose_Java_Label.setText(_translate("MCSL2_MainWindow", "选择Java"))
        self.Completed_Choose_Java_PushButton.setText(_translate("MCSL2_MainWindow", "选好了"))
        self.Update_Label.setText(_translate("MCSL2_MainWindow", "程序更新"))
        self.Update_Tip1_Label.setText(_translate("MCSL2_MainWindow", "MCSL 2发布新版本啦！你想更新吗？"))
        self.DoNotUpdate_PushButton.setText(_translate("MCSL2_MainWindow", "丑拒"))
        self.Update_PushButton.setText(_translate("MCSL2_MainWindow", "火速更新"))
        self.Update_Introduction_Title_Label.setText(_translate("MCSL2_MainWindow", "这是最新版本的说明："))
import MCSL2_Icon_rc
