# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\MCSLCode\MCSL2\MCSL2NewInterface\ui\Interface_download_build.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_buildListWidget(object):
    def setupUi(self, buildListWidget):
        buildListWidget.setObjectName("buildListWidget")
        buildListWidget.resize(284, 80)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(buildListWidget.sizePolicy().hasHeightForWidth())
        buildListWidget.setSizePolicy(sizePolicy)
        buildListWidget.setMinimumSize(QtCore.QSize(284, 80))
        buildListWidget.setMaximumSize(QtCore.QSize(284, 80))
        self.horizontalLayout = QtWidgets.QHBoxLayout(buildListWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TextWidget = QtWidgets.QWidget(buildListWidget)
        self.TextWidget.setObjectName("TextWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.TextWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.coreNameLabel = StrongBodyLabel(self.TextWidget)
        self.coreNameLabel.setObjectName("coreNameLabel")
        self.verticalLayout.addWidget(self.coreNameLabel)
        self.syncTimeLabel = StrongBodyLabel(self.TextWidget)
        self.syncTimeLabel.setObjectName("syncTimeLabel")
        self.verticalLayout.addWidget(self.syncTimeLabel)
        self.horizontalLayout.addWidget(self.TextWidget)
        self.DownloadBtn = PrimaryToolButton(buildListWidget)
        self.DownloadBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.DownloadBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.DownloadBtn.setObjectName("DownloadBtn")
        self.horizontalLayout.addWidget(self.DownloadBtn)

        self.retranslateUi(buildListWidget)
        QtCore.QMetaObject.connectSlotsByName(buildListWidget)

    def retranslateUi(self, buildListWidget):
        _translate = QtCore.QCoreApplication.translate
        buildListWidget.setWindowTitle(_translate("buildListWidget", "Form"))
        self.coreNameLabel.setText(_translate("buildListWidget", "[版本号]"))
        self.syncTimeLabel.setText(_translate("buildListWidget", "[同步时间]"))
from qfluentwidgets import CardWidget, PrimaryToolButton, StrongBodyLabel
