# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\MCSLCode\MCSL2\MCSL2NewInterface\ui\Interface_download_core.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_coreListWidget(object):
    def setupUi(self, coreListWidget):
        coreListWidget.setObjectName("coreListWidget")
        coreListWidget.resize(180, 51)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(coreListWidget.sizePolicy().hasHeightForWidth())
        coreListWidget.setSizePolicy(sizePolicy)
        coreListWidget.setMinimumSize(QtCore.QSize(180, 51))
        coreListWidget.setMaximumSize(QtCore.QSize(180, 51))
        self.horizontalLayout = QtWidgets.QHBoxLayout(coreListWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.coreTagLabel = PrimaryPushButton(coreListWidget)
        self.coreTagLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.coreTagLabel.setObjectName("coreTagLabel")
        self.horizontalLayout.addWidget(self.coreTagLabel)
        self.coreNameLabel = StrongBodyLabel(coreListWidget)
        self.coreNameLabel.setObjectName("coreNameLabel")
        self.horizontalLayout.addWidget(self.coreNameLabel)

        self.retranslateUi(coreListWidget)
        QtCore.QMetaObject.connectSlotsByName(coreListWidget)

    def retranslateUi(self, coreListWidget):
        _translate = QtCore.QCoreApplication.translate
        coreListWidget.setWindowTitle(_translate("coreListWidget", "Form"))
        self.coreTagLabel.setText(_translate("coreListWidget", "[标签]"))
        self.coreNameLabel.setText(_translate("coreListWidget", "[名称]"))
from qfluentwidgets import CardWidget, PrimaryPushButton, StrongBodyLabel
