# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\MCSLCode\MCSL2\MCSL2NewInterface\ui\Interface_download_version.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_versionListWidget(object):
    def setupUi(self, versionListWidget):
        versionListWidget.setObjectName("versionListWidget")
        versionListWidget.resize(140, 45)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(versionListWidget.sizePolicy().hasHeightForWidth())
        versionListWidget.setSizePolicy(sizePolicy)
        versionListWidget.setMinimumSize(QtCore.QSize(140, 45))
        versionListWidget.setMaximumSize(QtCore.QSize(140, 45))
        self.horizontalLayout = QtWidgets.QHBoxLayout(versionListWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.versionLabel = StrongBodyLabel(versionListWidget)
        self.versionLabel.setObjectName("versionLabel")
        self.horizontalLayout.addWidget(self.versionLabel)

        self.retranslateUi(versionListWidget)
        QtCore.QMetaObject.connectSlotsByName(versionListWidget)

    def retranslateUi(self, versionListWidget):
        _translate = QtCore.QCoreApplication.translate
        versionListWidget.setWindowTitle(_translate("versionListWidget", "Form"))
        self.versionLabel.setText(_translate("versionListWidget", "[版本]"))
from qfluentwidgets import CardWidget, StrongBodyLabel
