# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\MCSLCode\MCSL2\QtUI\playersControllerMainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_playersController(object):
    def setupUi(self, playersController):
        playersController.setObjectName("playersController")
        playersController.resize(398, 300)
        self.playersControllerMainWidget = QtWidgets.QWidget(playersController)
        self.playersControllerMainWidget.setGeometry(QtCore.QRect(20, 20, 350, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playersControllerMainWidget.sizePolicy().hasHeightForWidth())
        self.playersControllerMainWidget.setSizePolicy(sizePolicy)
        self.playersControllerMainWidget.setMinimumSize(QtCore.QSize(350, 241))
        self.playersControllerMainWidget.setObjectName("playersControllerMainWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.playersControllerMainWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.who = LineEdit(self.playersControllerMainWidget)
        self.who.setObjectName("who")
        self.gridLayout.addWidget(self.who, 0, 0, 1, 1)
        self.mode = ComboBox(self.playersControllerMainWidget)
        self.mode.setObjectName("mode")
        self.gridLayout.addWidget(self.mode, 0, 1, 1, 1)
        self.tipSmoothScrollArea = SmoothScrollArea(self.playersControllerMainWidget)
        self.tipSmoothScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tipSmoothScrollArea.setWidgetResizable(True)
        self.tipSmoothScrollArea.setObjectName("tipSmoothScrollArea")
        self.tipScrollAreaWidgetContents = QtWidgets.QWidget()
        self.tipScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -6, 313, 188))
        self.tipScrollAreaWidgetContents.setObjectName("tipScrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tipScrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.targetSelectorTipTitle = StrongBodyLabel(self.tipScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetSelectorTipTitle.sizePolicy().hasHeightForWidth())
        self.targetSelectorTipTitle.setSizePolicy(sizePolicy)
        self.targetSelectorTipTitle.setObjectName("targetSelectorTipTitle")
        self.verticalLayout.addWidget(self.targetSelectorTipTitle)
        self.targetSelectorTip = BodyLabel(self.tipScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetSelectorTip.sizePolicy().hasHeightForWidth())
        self.targetSelectorTip.setSizePolicy(sizePolicy)
        self.targetSelectorTip.setObjectName("targetSelectorTip")
        self.verticalLayout.addWidget(self.targetSelectorTip)
        self.playersTipTitle = StrongBodyLabel(self.tipScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playersTipTitle.sizePolicy().hasHeightForWidth())
        self.playersTipTitle.setSizePolicy(sizePolicy)
        self.playersTipTitle.setObjectName("playersTipTitle")
        self.verticalLayout.addWidget(self.playersTipTitle)
        self.playersTip = BodyLabel(self.tipScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playersTip.sizePolicy().hasHeightForWidth())
        self.playersTip.setSizePolicy(sizePolicy)
        self.playersTip.setObjectName("playersTip")
        self.verticalLayout.addWidget(self.playersTip)
        self.tipSmoothScrollArea.setWidget(self.tipScrollAreaWidgetContents)
        self.gridLayout.addWidget(self.tipSmoothScrollArea, 1, 0, 1, 2)

        self.retranslateUi(playersController)
        QtCore.QMetaObject.connectSlotsByName(playersController)

    def retranslateUi(self, playersController):
        _translate = QtCore.QCoreApplication.translate
        playersController.setWindowTitle(_translate("playersController", "Form"))
        self.who.setPlaceholderText(_translate("playersController", "填写玩家名或目标选择器"))
        self.targetSelectorTipTitle.setText(_translate("playersController", "目标选择器提示:"))
        self.targetSelectorTip.setText(_translate("playersController", "@p - 最近的玩家(在控制台可能无法使用)\n"
"@r - 随机玩家\n"
"@a - 所有玩家\n"
"@e - 所有实体(不包括死亡实体)\n"
"@s - 命令执行者(控制台不可用)"))
        self.playersTipTitle.setText(_translate("playersController", "当前在线玩家：(可能不准确)"))
        self.playersTip.setText(_translate("playersController", "[在线玩家列表]"))
from qfluentwidgets import BodyLabel, ComboBox, LineEdit, SmoothScrollArea, StrongBodyLabel
