# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\MCSLCode\MCSL2\QtUI\Downloads\newDownloadProgressWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_downloadingProgressWidget(object):
    def setupUi(self, downloadingProgressWidget):
        downloadingProgressWidget.setObjectName("downloadingProgressWidget")
        downloadingProgressWidget.resize(300, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(downloadingProgressWidget.sizePolicy().hasHeightForWidth())
        downloadingProgressWidget.setSizePolicy(sizePolicy)
        downloadingProgressWidget.setMinimumSize(QtCore.QSize(300, 100))
        downloadingProgressWidget.setMaximumSize(QtCore.QSize(300, 120))
        downloadingProgressWidget.setWindowTitle("")
        self.gridLayout_2 = QtWidgets.QGridLayout(downloadingProgressWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.infoWidget = QtWidgets.QWidget(downloadingProgressWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoWidget.sizePolicy().hasHeightForWidth())
        self.infoWidget.setSizePolicy(sizePolicy)
        self.infoWidget.setObjectName("infoWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.infoWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.fileNameLabel = BodyLabel(self.infoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileNameLabel.sizePolicy().hasHeightForWidth())
        self.fileNameLabel.setSizePolicy(sizePolicy)
        self.fileNameLabel.setMinimumSize(QtCore.QSize(196, 18))
        self.fileNameLabel.setMaximumSize(QtCore.QSize(196, 18))
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.gridLayout.addWidget(self.fileNameLabel, 0, 0, 1, 2)
        self.progressNum = CaptionLabel(self.infoWidget)
        self.progressNum.setObjectName("progressNum")
        self.gridLayout.addWidget(self.progressNum, 2, 1, 1, 1)
        self.ProgressBar = ProgressBar(self.infoWidget)
        self.ProgressBar.setProperty("value", 40)
        self.ProgressBar.setVal(40.0)
        self.ProgressBar.setObjectName("ProgressBar")
        self.gridLayout.addWidget(self.ProgressBar, 2, 0, 1, 1)
        self.downloadExtraInfoLabel = BodyLabel(self.infoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadExtraInfoLabel.sizePolicy().hasHeightForWidth())
        self.downloadExtraInfoLabel.setSizePolicy(sizePolicy)
        self.downloadExtraInfoLabel.setMinimumSize(QtCore.QSize(196, 18))
        self.downloadExtraInfoLabel.setMaximumSize(QtCore.QSize(196, 18))
        self.downloadExtraInfoLabel.setObjectName("downloadExtraInfoLabel")
        self.gridLayout.addWidget(self.downloadExtraInfoLabel, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.infoWidget, 0, 0, 2, 1)
        self.cancelBtn = PushButton(downloadingProgressWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBtn.sizePolicy().hasHeightForWidth())
        self.cancelBtn.setSizePolicy(sizePolicy)
        self.cancelBtn.setMinimumSize(QtCore.QSize(61, 32))
        self.cancelBtn.setMaximumSize(QtCore.QSize(61, 32))
        self.cancelBtn.setObjectName("cancelBtn")
        self.gridLayout_2.addWidget(self.cancelBtn, 0, 1, 1, 1)
        self.pauseBtn = PushButton(downloadingProgressWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pauseBtn.sizePolicy().hasHeightForWidth())
        self.pauseBtn.setSizePolicy(sizePolicy)
        self.pauseBtn.setMinimumSize(QtCore.QSize(61, 32))
        self.pauseBtn.setMaximumSize(QtCore.QSize(61, 32))
        self.pauseBtn.setObjectName("pauseBtn")
        self.gridLayout_2.addWidget(self.pauseBtn, 1, 1, 1, 1)

        self.retranslateUi(downloadingProgressWidget)
        QtCore.QMetaObject.connectSlotsByName(downloadingProgressWidget)

    def retranslateUi(self, downloadingProgressWidget):
        _translate = QtCore.QCoreApplication.translate
        self.fileNameLabel.setText(_translate("downloadingProgressWidget", "[文件名]"))
        self.progressNum.setText(_translate("downloadingProgressWidget", "NaN%"))
        self.downloadExtraInfoLabel.setText(_translate("downloadingProgressWidget", "[大小]   [速度]"))
        self.cancelBtn.setText(_translate("downloadingProgressWidget", "取消"))
        self.pauseBtn.setText(_translate("downloadingProgressWidget", "暂停"))
from qfluentwidgets import BodyLabel, CaptionLabel, ProgressBar, PushButton
