name: pr代码检查

on: [pull_request]

permissions: write-all

jobs:

  build:

    strategy:

      fail-fast: false

      matrix:

        os:

          - macos-latest

          - ubuntu-latest

          - windows-latest

        architecture:

          - x64

          - x86

    runs-on: ${{ matrix.os }}

    steps:

      - name: Check-out repository

        uses: actions/checkout@v3

      - name: Setup Python

        uses: actions/setup-python@v4

        with:

          python-version: '3.8'

          cache: 'pip'

          cache-dependency-path: |

            requirements.txt

            requirements.dev.txt

      - name: Update Pip

        run: |

          python -m pip install pip setuptools -U

      - name: Install Deps for Linux

        if: runner.os == 'Linux'

        run: |

          sudo apt-get install -y libfuse2

      - name: Install Project Deps

        run: |

          python -m pip install -r requirements.txt -r requirements.dev.txt

      - name: Build Executable on Linux

        if: runner.os == 'Linux'

        run: >

          python -m nuitka

          --standalone

          --enable-plugin=pyqt5

          --onefile

          --output-dir=build

          --assume-yes-for-downloads

          --disable-console

          --linux-icon=MCSL2.ico

          --company-name="LxHTT"

          --product-name="MCSL 2"

          --file-version=2.0.0

          --product-version=2.0.0

          --file-description="MC Server Launcher 2"

          MCSL2.py

      - name: Build Executable on macOS

        if: runner.os == 'macOS'

        run: >

          python -m nuitka

          --standalone

          --enable-plugin=pyqt5

          --onefile

          --output-dir=build

          --assume-yes-for-download

          --disable-console

          --macos-app-mode=gui

          --macos-app-icon=MCSL2.ico

          --company-name="LxHTT"

          --product-name="MCSL 2"

          --file-version=2.0.0

          --macos-app-version=2.0.0

          --file-description="MC Server Launcher 2"

          --macos-create-app-bundle

          MCSL2.py

      - name: Build Executable on Windows

        if: runner.os == 'Windows'

        run: >

          python -m nuitka

          --mingw64

          --standalone

          --enable-plugin=pyqt5

          --onefile

          --output-dir=build

          --assume-yes-for-downloads

          --windows-disable-console

          --windows-icon-from-ico=MCSL2.ico

          --windows-company-name="LxHTT"

          --windows-product-name="MCSL 2"

          --windows-file-version=2.0.0

          --windows-product-version=2.0.0

          --windows-file-description="MC Server Launcher 2"

          MCSL2.py
